### ISSUE TITLE
Passer l'objet base dans l'environnement

### ISSUE THREAD

**Issue by pguerindon** [agilsport/ski#11]
Il faut passer l'objet base dans l'environnement dans les 2 cas suivants et pour la même raison :

1. quand on lance un scénario depuis la fenêtre des concurrents
2. quand on lance une édition qui chaine sur un script LUA

Dans la fonction main(t) appelée, quand on fait : 
base = base or sqlBase.Clone(), la base étant nil, tous les développements ultérieurs se font sur la base clonée. 
C'est le cas de la création des tables physiques qui auront été ajoutées dans la base clonée et donc si on revient sur le même scénario sans sortir de skiFFS, la table physique n'existe pas dans la base principale. Le script essaye de la recréer à tord et génère un message d'erreur MySQL disant que la table existe déjà.

Je n'ai pas testé mais il est probable que ce soit la même chose quand on fait un clic droit pour lancer la gestion des matrices. Il me semble que j'avais le même souci.

2 solutions : 

1. passer l'objet base
2. créer les tables au lancement de skiFFS

**Comment by agilsport** [comment]
Exact ... corrigé avec la 3.5d
