### ISSUE TITLE
Journal des inscriptions

### ISSUE THREAD

**Issue by StephCantal** [agilsport/ski#12]
sur le journal global des inscriptions je ne retrouve pas tous les concurrents et lors de l'ajout le nom de l'utilisateur ne se met pas 

il se met lors d'une modification

capture d'écran ci-dessous

![image](https://user-images.githubusercontent.com/91496539/139718920-08c7e6cb-2b72-42db-bd21-e181f712da80.png)

**Comment by agilsport** [comment]
Le bug venait que la recherche coureur non autorisé sur le web FFS, était accessible par le raccourci F3 ...
on peut inscrire plusieurs concurrents par paquets mais uniquement avec le transfert Cloud 
corrigé avec la version 3.5f
