### ISSUE TITLE
scenarios

### ISSUE THREAD

**Issue by StephCantal** [agilsport/ski#13]
se serais bien de mettre une boite de dialogue pour confirmer le lancement du scenarios car la liste est petite on ne sais pas si on est bien sur le bon et la en 1 eclair le tirage est refait sans etre sure d'avoir lancer le bon

**Comment by pguerindon** [comment]
Je m'en occupe

**Comment by agilsport** [comment]
C 'est plus dans le C++ qu'il faut le faire ... marche pour tous les scénarios ...

**Comment by agilsport** [comment]
OK fait avec la 3.4g

**Comment by agilsport** [comment]
hum la 3.5f
