### ISSUE TITLE
facture.lua

### ISSUE THREAD

**Issue by StephCantal** [agilsport/ski#16]
verifier la fonction page break dans le end (facture.lua)  il y a une page blanche qui se fait

**Comment by Mathieunorma** [comment]
Bonjour,

J'essaie de mettre en place la facturation pour la partie alpin, en m'inspirant largement des fichiers du fond

Il me reste 2 problèmes:

- La distance en KM qui reste sur le PDF
- Et la catégorie Dame qui est exclue de la facturation.

Y a t il des gratuités ? Et quels sont les critères pour le Fond

Merci

Mathieu

**Comment by StephCantal** [comment]
Bonjour 

 

J'ai modifier pour enlever la distance en alpin par contre regarder bien votre configuration car moi les dames y sont bien 

 

Pierre les intégreras dans la prochaine MAJ

 

Les factures fonctionne pour toutes les activités et sur le principe des épreuves 

 

Pour que je fasse une vérification envoyer moi votre SAV

 

STEPHANE

 

De : Mathieunorma ***@***.***> 
Envoyé : mardi 1 février 2022 10:44
À : agilsport/ski ***@***.***>
Cc : Stephane Sandrin ***@***.***>; Author ***@***.***>
Objet : Re: [agilsport/ski] facture.lua (Issue #16)

 

Bonjour,

J'essaie de mettre en place la facturation pour la partie alpin, en m'inspirant largement des fichiers du fond

Il me reste 2 problèmes:

*	La distance en KM qui reste sur le PDF
*	Et la catégorie Dame qui est exclue de la facturation.

Y a t il des gratuités ? Et quels sont les critères pour le Fond

Merci

Mathieu

**Comment by Mathieunorma** [comment]
Bonjour,

Merci de vous intéresser a mon problème.

Le soucis de facturation est: La catégorie U18=> Master, le tarif reste  à 0€ 

Je vous joins la course au format ZIP. J'espère que vous pourrais la lire, je débute sur le github

Mathieu 




[sos61.zip](https://github.com/agilsport/ski/files/7984700/sos61.zip)

**Comment by StephCantal** [comment]
Bonjour

 

Ci-joint une capture d'écran ça fonctionne bien et le tarif ce met a tt les épreuves.

 

 



 

Pour la valeur du tarif des U19 -> mast je pense que c'est juste que vous êtes pas sorti de la case car skiffs fonctionne comme Excell il faut bien sortir de la case pour que la valeur soit bien prise ne compte

 

Apres votre course est en saison 2021 du coup je suis pas sure que le filtre par épreuve soit au top a vérifier

 

stephane

 

De : Mathieunorma ***@***.***> 
Envoyé : mercredi 2 février 2022 09:27
À : agilsport/ski ***@***.***>
Cc : Stephane Sandrin ***@***.***>; Author ***@***.***>
Objet : Re: [agilsport/ski] facture.lua (Issue #16)

 

Bonjour,

Merci de vous intéresser a mon problème.

Le soucis de facturation est: La catégorie U18=> Master, le tarif reste à 0€

Je vous joins la course au format ZIP. J'espère que vous pourrais la lire, je débute sur le github

Mathieu

sos61.zip <https://github.com/agilsport/ski/files/7984700/sos61.zip>

**Comment by Mathieunorma** [comment]
Bonjour,

Merci du temps passé, tout fonctionne.

C'était effectivement un problème d'utilisateur, je ne sortais de la case pour valider le tarif.

Merci du coup de main
