### ISSUE TITLE
Ré-homologation BTR - Rapport accident

### ISSUE THREAD

**Issue by FFSmarlene** [agilsport/ski#19]
Il faut remettre la ré-homologation des résultats (peut être créer un nouvel onglet) mais également si l’évènement a fait l’objet d’une déclaration d’accident (Oui / Non) que l'on ne retrouve pas dans l'onglet "Homologation" mais une réponse est présente lors de l'impression du rapport

**Comment by agilsport** [comment]
Ok je remet en place idem FFSSKI ...

**Comment by agilsport** [comment]
mise en place avec la version 4.0f
Dans l'onglet Homologation , le bouton dans la barre d'outils "Re-Homologation" existe ...
Fonctionnement idem FFSSKI
