### ISSUE TITLE
Code regroupement POOL

### ISSUE THREAD

**Issue by pguerindon** [agilsport/ski#20]
Il faut permettre la saisie du code regroupement POOL pour les courses FIS même si on ne le met pas dans la liste déroulante via le combotable. Il est indispensable pour gérer les courses de type POOL afin de gérer les officiels à mettre sur les entry form FIS.
Soit on le rajoute dans la table soit on le rajoute en dernière position par un append. 
Si on décide de le mettre dans la table,  ça pourrait être fait avec la prochaine liste. Pour le moment Philippe Martin s'en sort en utilisant une vieille course POOL.
C'est bloquant à l'heure actuelle.

**Comment by agilsport** [comment]
Si on ajoute le regroupement "POOL" pour l'activité "ALP" et l'entité "FIS" ça corrige le problème ...
En attendant c'est pas trop bloquant car tout utilisateur peut bien créer tous les regroupement qu'il veut ... (c'est juste Officiel="N") et ainsi le retrouver dans la liste ?

**Comment by pguerindon** [comment]
Quand on essaye de créer un nouveau regroupement, il faut penser à afficher la colonne Libelle_impression afin de la remplir.
Le champs ne peut pas être égal à NULL.
C'est pour ça que je bloquais.
Le mieux serait peut-être d'afficher la colonne à la saisie.

**Comment by agilsport** [comment]
On peut faire les 2 
1)  Ajouter cette colonne dans la grille
2) cette colonne peut tout à fait accepter les champs "null"

**Comment by pguerindon** [comment]
OK , Je ferme
