### ISSUE TITLE
Collage spécial

### ISSUE THREAD

**Issue by StephCantal** [agilsport/ski#21]
Si on prend un tableau ou a la première colonne est vide avec juste l'entête ou partiellement rempli on se retrouve avec un décalage de colonne dans les lignes

**Comment by agilsport** [comment]
Oui corrigé ... en place dans la prochaine version 4.0h ou sup ...

**Comment by StephCantal** [comment]
ok merci

**Comment by agilsport** [comment]
version 4.0h correction
