### ISSUE TITLE
souci transfert webffs/base locale

### ISSUE THREAD

**Issue by AlainDeschildre** [agilsport/ski#24]
Problème sur le transfert des fichiers webffs/base locale. Quand on est sur la coures webffs/concurrents on sélectionne tous les concurrents. On fait "Transfert des concurrents web vers course locale" on rentre le numéro de la course sur base locale. Quand on va sur la course locale/concurrents il y a 0 inscrits. Les concurrents précédemment inscrits en local ont disparus ainsi que ceux transférés. Il faut fermer le logiciel, le ré ouvrir pour récupérer tous les concurrents.

**Comment by pguerindon** [comment]
Bonsoir,
Je ne rencontre pas ce problème.
Est-ce qu'il y a cohérence entre les paramètres de la course locale et ceux de la course du web FFS ?
Entité, Activité, Sexe etc ?
De mon côté tout marche bien.
Notez la version actuelle de votre skiFFS (pour revenir en arrière éventuellement) et téléchargez la dernière version du logiciel pour voir si vous rencontrez le même souci.
On s'appelle lundi matin vers 10h
06 07 13 34 11

**Comment by AlainDeschildre** [comment]
Ok vers 10 h. A tout à l'heure.
Alain
