### ISSUE TITLE
Erreur en-tête editions liste hommes

### ISSUE THREAD

**Issue by AlainDeschildre** [agilsport/ski#26]
Quand on édite Liste des participants/ Par comité/Imprimer/filtrage/ FRA/valider/Homme/valider/valider   L'en-tête est intitulé Dames .
 S'il n'y a qu'un filtrage (par exemple) Liste des participants par nation/imprimer/Hommes/Sélection l'en-tête est correct.

**Comment by pguerindon** [comment]
La remarque est justifiée.
Dans l'édition des participants, le libellé prenait toujours celui de la première épreuve.
Maintenant,  si on place un "Titre" dans le filtrage des coureurs et même si on ne filtre rien, ce titre prend la place du libellé de la première épreuve.
Pour la prochaine version ...

**Comment by pguerindon** [comment]
Je clos ce cas.
