### ISSUE TITLE
Conversion des codes

### ISSUE THREAD

**Issue by pguerindon** [agilsport/ski#29]
La conversion des codes ne semble pas marcher .
Sur une course, Je veux passer des codes FFS aux codes FIS et rien ne se passe.
Dans la liste déroulante des conversions possibles, de FIS vers FFS et de FFS vers FIS semblent inversés.

**Comment by agilsport** [comment]
Il y a un soucis de libellé dans les messages effectivement ...  c'est corrigé ...
Par contre ensuite ça me semble ok ... tout est basé sur la table "Correspondance" qui ne doit pas être vide et donc bien charger les licences FFS et FIS ...

**Comment by pguerindon** [comment]
Ca marche parfaitement pout convertir des codes FIS en codes FFS mais pas l'inverse ce dont j'avais besoin. 
Je l'en suis sorti avec un FFSSKI.

**Comment by pguerindon** [comment]
Corrigé ce jour. Je ferme

**Comment by agilsport** [comment]
corrigé avec la version 4.0p ...
