### ISSUE TITLE
Fenetre filtrage épreuve

### ISSUE THREAD

**Issue by StephCantal** [agilsport/ski#3]
faire une fonction pour activer la fenêtre filtrage épreuves et fltage depuis une edition .Lua (par exemple l'edition des couloirs) qui se lance depuis editionFond.xml

**Comment by agilsport** [comment]
Ok avec la 4.0g ...
J'ai modifié le couloir.lua et editionFOND.xml avec le mot clé : filter="before" pour un premier exemple

**Comment by StephCantal** [comment]
Ca a l’air de jouer

 

merci

 

De : Agil ***@***.***> 
Envoyé : vendredi 12 novembre 2021 20:04
À : agilsport/ski ***@***.***>
Cc : Stephane Sandrin ***@***.***>; Author ***@***.***>
Objet : Re: [agilsport/ski] Fenetre filtrage épreuve (Issue #3)

 

Closed #3 <https://github.com/agilsport/ski/issues/3> .
