### ISSUE TITLE
Transfert de concurrents

### ISSUE THREAD

**Issue by AlainDeschildre** [agilsport/ski#32]
Bonjour
Quand je vais dans concurrents, je sélectionne tous les concurrents et je choisis transfert des concurrents, je saisis le numéro de l'évènement, confirme le transfert, un message me dit que les concurrents sont transférés mais ma course de destination reste vide.

**Comment by pguerindon** [comment]
Ceci a été corrigé dans la version 4.0i.
Une version sera rapidement disponible en Auto Update. Elle reprendra toutes les correction des versions intermédiaires de développement.

**Comment by pguerindon** [comment]
Corrigé
