### ISSUE TITLE
Changement de liste fenêtre des concurrents

### ISSUE THREAD

**Issue by FFSmarlene** [agilsport/ski#33]
Si je change de numéro de liste sur un évènement existant, la liste que j'ai sélectionnée est bien prise en compte mais lorsque je recherche un coureur pour l'inscrire, les points affichés associés à ce coureur ne sont pas ceux de cette nouvelle liste. Par contre si je ressort de la fenêtre des concurrents et que je le rappelle je retrouve bien les points de la liste que j'avais choisie.

**Comment by agilsport** [comment]
Oui c'est corrigé avec la version 4.0p
