### ISSUE TITLE
grille des compétitions dans le calendrier

### ISSUE THREAD

**Issue by StephCantal** [agilsport/ski#34]
si on vas dans le calendrier et que l'on rajoute une colonne elle s'affiche pas toujours mais surtout si on fait enregistrement du contexte ca ne fonctionne pas si je sort et re rentre la colonne ne s'affiche plus

**Comment by pguerindon** [comment]
Stephane, l'enregistrement du contexte est fait pour chaque onglet / sous-onglet de l'affichage tant au niveau des courses que pour le calendrier. Est-ce que tu l'as fait pour tous les onglets ?

**Comment by StephCantal** [comment]
Ok ça a l air de fonctionner mais il a fallu que je mis prenne à plusieurs fois
