### ISSUE TITLE
Prise en compte du temps maxi

### ISSUE THREAD

**Issue by pguerindon** [agilsport/ski#36]
La valeur définie devrait être volatile et être valide uniquement tant qu'on reste dans la fenêtre de chronométrage.
Si on sort du chronométrage et qu'on y revient, le temps maxi défini précédemment est remplacé par une autre valeur au lieu d'être à blanc. Le résultat risque d'être imprévisible.

**Comment by agilsport** [comment]
Corrigé avec la 4.0s
