### ISSUE TITLE
SkiFFS et Alge Timy 3

### ISSUE THREAD

**Issue by JKZ2** [agilsport/ski#40]
Bonjour, 

Je n'arrive pas a faire marcher le chrono Alge Timy3 (USB) avec SkiFFS. J'ai mis le logiciel a jour 

   Alge Version NFS  V21B2 driver 2.76 
  SkiFFS version 4.0v (Win32)

J'ai essaye de re-installer SkiFFS, l'ALGE marche parfaitement sur le PC avec l'interface EXCEL fourni par Alge et SkiAlpPro
Il n'y a pas de message d'erreur, juste les impulsions qui ne passe pas en mode chrono - je n'ai fait aucune redirection dans la configuration

**Comment by JKZ2** [comment]
Au démarrage du Chrono j'ai une erreur SQL ... peut être que cela a un rapport mais le message existe quelque soit le chrono connecte (par exemple TAG CP 545 qui marche parfaitement)

Text	
sqlMySQL::Query : Bad request	
Update Context Set Best_identity = '', Best_time = '', Best_timeMs = -1 Where ID = 1	
Error 1054 : Unknown column 'Best_timeMs' in 'field list'

**Comment by agilsport** [comment]
Pour faire marcher le Timy il faut installer 2 active X fourni par Alge 
Sur la page d'Agil : https://agil.fr/ski il y a les 2 driver à télécharger ALGEUSB230.exe  ALGEUSB276.exe ...

Pour la deuxième erreur , c'est votre base TV qui est trop ancienne ...
Pour résoudre 2 solutions :
1) Vous réinstallez le skiFFS complétement 
2) Vous arretez le laragon, vous supprimez la base tv (skiFFS\laragon\data\mysql\tv) et relancer le laragon  (la base va se recréer automatiquement)
