### ISSUE TITLE
Calcul de la pénalité en alpin proposé dans le menu des éditions

### ISSUE THREAD

**Issue by FFSmarlene** [agilsport/ski#45]
Si je calcule la pénalité à partir de "Edition - Calcul de pénalité" alors que mon évènement comprend 2 épreuves (1 H. et 1 D.) elle va être calculée avec les hommes et les dames. On n'a plus le choix par épreuve, elle va donc être fausse.
Ne pourrait-on pas lorsque l'on passe par l'édition pour calculer la pénalité être renvoyé directement dans l'onglet homologation ou avoir le choix de sélectionner par épreuve comme c'était le cas sur FFSSKI.

**Comment by pguerindon** [comment]
Et si on supprimait purement et simplement la possibilité de calculer une pénalité à partir des éditions. 
Il est beaucoup plus naturel de le faire à partir de l'en-tête où toutes les épreuves sont listées.
C'est en plus beaucoup plus rapide dès lors que le nombre des épreuves dépasse 3.

**Comment by rolandalsace** [comment]
+1 avec Philippe.
Cette une source d'erreur fréquente cette édition qui calcule le pénalité toutes épreuves confondues.

**Comment by pguerindon** [comment]
Le calcul de la pénalité est retiré des éditions alpines
