### ISSUE TITLE
Double affichage dans le Live FFS (je ne peux pas tester pour la FIS mais les trames sont bien doublées)

### ISSUE THREAD

**Issue by pguerindon** [agilsport/ski#50]
Quand plusieurs ordinateurs sont en réseau, en base de temps et pas en lecture seule, les affichages sur le Live FFS sont multipliées car les notifications sont envoyées par chacun d'eux entraînant un envoi des trames XML. C'est du reste le principe des notifications en réseau. Il faudra trouver une solution.

**Comment by Mathieunorma** [comment]
J'ai le même problème avec un PC seul. En manche 2 le même coureur est 2 fois en course.
Je n'ai pas pu testé en FIS également

**Comment by pguerindon** [comment]
Merci de me faire passer une sauvegarde de la course
 
Philippe Guérindon 
Envoyé depuis l'application Mail Orange
----------------Le 11/03/2022, à 15:50, Mathieunorma a écrit :

Tous les service de réseaux sont désactivés.

Et le "phénomène" ne se produit que sur la manche 2.

En manche 1 tous se déroule normalement

**Comment by Mathieunorma** [comment]
J'ai eu le problème sur trois courses.

Je joins les trois course
[sos148.zip](https://github.com/agilsport/ski/files/8237305/sos148.zip)
s

**Comment by pguerindon** [comment]
Je vais essayer de comprendre.

Sur aucun des live en cours, il n’y a de doublon.

Philippe

 

 

 

De : Mathieunorma ***@***.***> 
Envoyé : samedi 12 mars 2022 09:39
À : agilsport/ski ***@***.***>
Cc : Philippe Guérindon ***@***.***>; Author ***@***.***>
Objet : Re: [agilsport/ski] Double affichage dans le Live FFS (je ne peux pas tester pour la FIS mais les trames sont bien doublées) (Issue #50)

 

J'ai eu le problème sur trois courses.

Je joins les trois course
sos148.zip <https://github.com/agilsport/ski/files/8237305/sos148.zip> 
s

**Comment by Mathieunorma** [comment]
J ai vu sur une course ce matin.
Desole pour la qualité,  c est de screenshot de mon telephone
![Screenshot_20220312-124134_Chrome](https://user-images.githubusercontent.com/97058534/158017174-2a30416f-1ff4-4c9e-a25c-07b41890cc07.jpg)
![Screenshot_20220312-124123_Chrome](https://user-images.githubusercontent.com/97058534/158017175-f19d50eb-8f21-459f-853b-275bec015dfc.jpg)

**Comment by StephCantal** [comment]
bonjour

le problème à été résolu il suffit juste a pierre de mettre a jour le live FFS et ca à été déjà fait peu être

**Comment by pguerindon** [comment]
Problème résolu
