### ISSUE TITLE
Recherche de coureurs dans listes FFS

### ISSUE THREAD

**Issue by PhilippeMorteau** [agilsport/ski#51]
Lorsque l'on recherche certains coureurs par leur nom et leur prénom on ne les trouve pas, il faut taper obligatoirement leur numéro de licence FFS pour les voir apparaitre : exemple : LAMBERT TIMOTHEE ou PERRIN Maxence. Avez vous une solution (caractère caché ou autre ?) pour retrouver ces coureurs à partir de leur identité ? 
Autre cas si l'on cherche ANDRE Léane, on trouve à partir de Léane mais pas à partir d'ANDRE…
Merci de votre aide. Philippe

**Comment by pguerindon** [comment]
Quand on recherche un coureur par son identité, dans la zone "Nom", il est indiquéà droite de la loupe : 
recherche nom, prénom 
Il suffit de taper lam,ti pour n'avoir plus que le choix entre 2 coureurs.
Tout se fait sur la zone de recherche Nom.
Si on tape "TI" dans la zone prénom, on obtient tous les coureurs dont le prénom commence par "Ti"
