### ISSUE TITLE
modif éditionALP.xml  (sera clôturée d'ici  quelques jours)

### ISSUE THREAD

**Issue by Phil73200** [agilsport/ski#54]
Salut Philippe,

J’ai très légèrement modifié ton travail pour prendre en compte le nombre d'étrangers payant sur l'édition des statistiques de course pour prendre en compte les courses de type NC, ou F en l'occurrence. 
je t'envoi le fichier modifié renommé : éditionALPphil. xml dans ton filezilla PG

voici la modif: ajout de : "or regroupement == 'F' then"

for i = 0, body:GetNbRows() -1 do
					comitelu = body:GetCell('Comite', i);
					if regroupement == 'FIS' or regroupement == 'F' then
						etrangers_gratuits = body:GetCounterValue('Nation', 'AUT') + body:GetCounterValue('Nation', 'AND') + body:GetCounterValue('Nation', 'ITA') + body:GetCounterValue('Nation', 'MON') + body:GetCounterValue('Nation', 'SUI');
						etrangers_payants = etrangers - etrangers_gratuits;

**Comment by pguerindon** [comment]
J'ai remis sur le FTP le fichier modifié par mes soins :
if regroupement == 'FIS' or regroupement == 'F' then
devient 
if regroupement:In('FIS', F')  then

moins verbeux en cas de modification.

Cette fonction In() n'est pas une fonction native du langage LUA. Elle a été ajouté dans skiFFS comme beaucoup d'autres.
