### ISSUE TITLE
Scénarios

### ISSUE THREAD

**Issue by pguerindon** [agilsport/ski#9]
on ne récupère pas les paramètres dans la fonction main des scripts.

**Comment by StephCantal** [comment]
avec la version 3.5b chez moi le bouton Scénario est inactif

**Comment by agilsport** [comment]
corrigé avec la version 3.5c ...
on passe une table et non plus une liste de clés ...
Pour Stéphane ce n'est pas un bug mais juste que sur son pc il n'a pas de scenario ...
comme on en livrera au moins 3 (1 ESF + 2 FFS) le menu ne sera jamais vide
